# all parameters in mm's and gramms

STICK_LENGTH = 370.
STICK_HEIGHT = 59.
STICK_MASS = 196.

MOTOR_MASS = 67.
MOTOR_DISTANCE = 158.
MOTOR_HEIGHT = 50.

REGULATOR_MASS = 24.
REGULATOR_DISTANCE = 70.
REGULATOR_HEIGHT = 32.

CENTER_AXIS_IDENT = 21.8
PILLAR_HEIGH = 85.

MAX_ANGLE = 14.5 # in degrees